### ISSUE TITLE
add .hover and link to icons on lower nav

### ISSUE THREAD

**Issue by cmhleveret** [cmhleveret/portfolio#6]

**Comment by abitsalihu** [comment]
I would like to help with this issue, what kind of hover effect would you want and please provide the link to be attached with the icons!

**Comment by cmhleveret** [comment]
> I would like to help with this issue, what kind of hover effect would you want and please provide the link to be attached with the icons!

Thank you again for the offer!! The issue has already been resolved. Again I appreciate the offer to help!
